version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./docker/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./docker/wordpress_data:/var/www/html
      - ./assets:/var/www/html/wp-content/plugins/woocommerce-gateway-fio/assets
      - ./includes:/var/www/html/wp-content/plugins/woocommerce-gateway-fio/includes
      - ./languages:/var/www/html/wp-content/plugins/woocommerce-gateway-fio/languages
      - ./gulpfile.js:/var/www/html/wp-content/plugins/woocommerce-gateway-fio/gulpfile.js
      - ./package.json:/var/www/html/wp-content/plugins/woocommerce-gateway-fio/package.json
      - ./readme.txt:/var/www/html/wp-content/plugins/woocommerce-gateway-fio/readme.txt
      - ./woocommerce-gateway-fio.php:/var/www/html/wp-content/plugins/woocommerce-gateway-fio/woocommerce-gateway-fio.php
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      XDEBUG_CONFIG: remote_host=host.docker.internal
